FROM openjdk:8
ADD react-and-spring-data-rest-security-0.0.1-SNAPSHOT.jar react-and-spring-data-rest-security-0.0.1-SNAPSHOT.jar
EXPOSE 8085
ENTRYPOINT ["java", "-jar", "react-and-spring-data-rest-security-0.0.1-SNAPSHOT.jar"]